version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=bookstack
    - MYSQL_USER=bookstack
    - MYSQL_PASSWORD=secret
    volumes:
    - ./mysql:/var/lib/mysql

  bookstack:
    image: tchiotludo/docker-bookstack-fpm
    depends_on:
    - mysql
    environment:
    - DB_HOST=mysql
    - DB_DATABASE=bookstack
    - DB_USERNAME=bookstack
    - DB_PASSWORD=secret
    volumes:
    - ./uploads:/var/www/BookStack/public/uploads

  nginx:
    image: nginx
    volumes_from:
    - bookstack:ro
    depends_on:
    - bookstack
    volumes:
      - ./bookstack:/etc/nginx/conf.d/default.conf
    ports:
    - "8080:80"
